In [35]:
import torch
import torch.nn as nn

In [36]:
logits = torch.tensor([1, 0.9, 0.8, 0.2, 0.1, 0.1])
probs = torch.softmax(logits, dim=0)
torch.argmax(probs, dim=-1)

tensor(0)

Multinominal

In [37]:
ids = [torch.multinomial(probs, num_samples=1).item() for i in range(1000)]
counts = torch.bincount(torch.tensor(ids))
counts

tensor([219, 228, 192, 138, 113, 110])

Temperature

In [38]:
def temperature(logits, temp):
    probs = nn.functional.softmax(logits / temp, dim=0)
    ids = [torch.multinomial(probs, num_samples=1).item() for i in range(1000)]
    counts = torch.bincount(torch.tensor(ids))
    return counts

In [39]:
temperature(logits, 1)

tensor([240, 215, 212, 130, 111,  92])

In [40]:
temperature(logits, 0.1)

tensor([651, 263,  86])

In [41]:
temperature(logits, 10)

tensor([149, 175, 186, 153, 171, 166])

Top k

In [42]:
top_logits, top_pos=torch.topk(logits,k=3)
top_logits

tensor([1.0000, 0.9000, 0.8000])

In [43]:
def top_k(logits,top_k):
    top_logits, top_pos=torch.topk(logits,top_k)
    filtered=torch.where(
        logits<top_logits[-1],
        input=torch.tensor(float("-inf")),
        other=logits
    )
    return filtered

In [44]:
top_k(logits,3)

tensor([1.0000, 0.9000, 0.8000,   -inf,   -inf,   -inf])